Cleanup: prefer CHECK_EQ(a, b) to CHECK(a == b)
3rdparty/eventuals-grpc pull request #61
Opened 2022-01-11 17:59 UTC by CodingCanuck

The former prints more useful error messages containing both values. See
https://github.com/google/glog#check-macros.

2022-01-11 18:05 UTC, sp33drac3r requested changes
> *[Reviewable](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CodingCanuck and @sp33drac3r)

___
*[test/client-death-test.cc, line 52 at r1](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61#-Mt9J-DWEeeg8NUdNUyB:-Mt9J-DWEeeg8NUdNUyC:b9slu86) ([raw file](https://github.com/3rdparty/eventuals-grpc/blob/04043ef53ead3b81fe07ec3bd916c462af93705b/test/client-death-test.cc#L52)):*
> ```cpp
>   auto notify_forked = [&]() {
>     int _ = 1;
>     CHECK_GT(write(pipes.fork[1], &_, sizeof(int)), 0);
> ```

This is a comment! 


<!-- Sent from Reviewable.io -->

2022-01-11 18:07 UTC, sp33drac3r approved these changes
> *[Reviewable](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @sp33drac3r)



<!-- Sent from Reviewable.io -->

2022-01-11 18:07 UTC, CodingCanuck reviewed
> *[Reviewable](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sp33drac3r)

___
*[test/client-death-test.cc, line 51 at r1](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61#-Mt9Jh11EyXug7M21JUe:-Mt9Jh11EyXug7M21JUf:b-y7p4cp) ([raw file](https://github.com/3rdparty/eventuals-grpc/blob/04043ef53ead3b81fe07ec3bd916c462af93705b/test/client-death-test.cc#L51)):*
> ```cpp
> 
>   auto notify_forked = [&]() {
>     int _ = 1;
> ```

But what about this comment?
___
*[test/client-death-test.cc, line 52 at r1](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61#-Mt9J-DWEeeg8NUdNUyB:-Mt9JWNp06QHfkYQJYrA:btd519t) ([raw file](https://github.com/3rdparty/eventuals-grpc/blob/04043ef53ead3b81fe07ec3bd916c462af93705b/test/client-death-test.cc#L52)):*
<details><summary><i>Previously, sp33drac3r (Riley Scheid) wrote…</i></summary><blockquote>

This is a comment! 
</blockquote></details>

I agree!


<!-- Sent from Reviewable.io -->

2022-01-11 18:08 UTC, sp33drac3r reviewed
> *[Reviewable](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @CodingCanuck and @sp33drac3r)

___
*[test/client-death-test.cc, line 51 at r1](https://reviewable.io/reviews/3rdparty/eventuals-grpc/61#-Mt9Jh11EyXug7M21JUe:-Mt9JsOyCmb011cuzUIM:b-5j3dcb) ([raw file](https://github.com/3rdparty/eventuals-grpc/blob/04043ef53ead3b81fe07ec3bd916c462af93705b/test/client-death-test.cc#L51)):*
<details><summary><i>Previously, CodingCanuck (Alex McCarthy) wrote…</i></summary><blockquote>

But what about this comment?
</blockquote></details>

`does_this == code`?


<!-- Sent from Reviewable.io -->

2022-01-13 20:15 UTC, CodingCanuck commented
I'm going to merge this, since I think we've finished taking our initial look at reviewable.io.

2022-01-13 20:15 UTC, merged