Introduce build_and_test.yml for building and running tests
3rdparty/eventuals-grpc pull request #63
Opened 2022-01-20 11:52 UTC by ArthurBandaryk

Since we can use `matrix` in the workflow, that's why there is no more any need to have 3 separate .yml files which do just the same work except current running OS.

2022-01-21 06:04 UTC, benh requested changes
See comments for similar review in 3rdparty/eventuals.

2022-01-21 16:36 UTC, benh approved these changes

2022-01-25 11:23 UTC, ArthurBandaryk commented
@benh , could you please remove old `Build and Test` action in the branch protection rules in Settings?

2022-01-26 16:25 UTC, benh approved these changes

2022-01-26 16:25 UTC, benh commented on .github/workflows/build_and_test.yml
> +        os: ["macos-latest", "ubuntu-latest"]
Can you move the comment that we're not using Windows because of a known build error down here please?

2022-02-01 19:33 UTC, merged